/**
 * Serialize a composed plugin-row array to the `cordis.yml` text the
 * `dsh-jsonrpc-agent` runtime bin reads. Deliberately plain YAML — no
 * `!!js` expressions: this SDK resolves every dynamic value (env vars,
 * platform checks, computed paths) in TypeScript before composing the row
 * array, so the generated file is inert data the Cordis Loader parses with
 * no code execution of its own.
 */
import { stringify } from 'yaml'
import type { PluginRow } from './rows.ts'

const HEADER =
  '# Generated by @researchcraft/dsh-harness-sdk. Do not hand-edit — regenerate via HarnessRuntime.\n'

export function serializeCordisTree(rows: readonly PluginRow[]): string {
  return HEADER + stringify(rows, { indent: 2, lineWidth: 0 })
}
